const sampleStudents = [
  {
    studentName: "Md Shazzad Hossain",
    studentImage: "",
    studentAge: 24,
    studentFatherName: "Md Jahangir Mia",
    studentMotherName: "Shahinur Begum",
    studentEmail: "shazzadmail1@gmail.com",
    studentContact: "01766032333",
    studentGuardianContact: "01816898357",
    studentMailingAddress:
      "House: 37, Lane: 5, Block: A, Section: 6, Mirpur, Dhaka: 1216",
  },
  {
    studentName: "Mst Farzana Akter",
    studentImage: "",
    studentAge: 22,
    studentFatherName: "Md Aminul Islam",
    studentMotherName: "Rehana Begum",
    studentEmail: "farzana.akter22@gmail.com",
    studentContact: "01712345678",
    studentGuardianContact: "01923456789",
    studentMailingAddress:
      "House: 12, Road: 3, Block: C, Bashundhara R/A, Dhaka: 1229",
  },
  {
    studentName: "Md Rakibul Hasan",
    studentImage: "",
    studentAge: 23,
    studentFatherName: "Md Abdul Latif",
    studentMotherName: "Nasrin Akter",
    studentEmail: "rakibul.hasan23@gmail.com",
    studentContact: "01811223344",
    studentGuardianContact: "01911223344",
    studentMailingAddress: "House: 5, Lane: 2, Sector: 10, Uttara, Dhaka: 1230",
  },
  {
    studentName: "Tasnim Jahan",
    studentImage: "",
    studentAge: 21,
    studentFatherName: "Md Nurul Amin",
    studentMotherName: "Salma Khatun",
    studentEmail: "tasnim.jahan21@gmail.com",
    studentContact: "01755667788",
    studentGuardianContact: "01655667788",
    studentMailingAddress: "House: 21, Road: 7, Dhanmondi, Dhaka: 1209",
  },
  {
    studentName: "Md Imran Khan",
    studentImage: "",
    studentAge: 25,
    studentFatherName: "Md Shahidul Islam",
    studentMotherName: "Ferdousi Begum",
    studentEmail: "imran.khan25@gmail.com",
    studentContact: "01677889900",
    studentGuardianContact: "01877889900",
    studentMailingAddress: "House: 9, Block: D, Banasree, Rampura, Dhaka: 1219",
  },
  {
    studentName: "Sumaiya Islam",
    studentImage: "",
    studentAge: 20,
    studentFatherName: "Md Kamal Uddin",
    studentMotherName: "Rowshan Ara",
    studentEmail: "sumaiya.islam20@gmail.com",
    studentContact: "01911002233",
    studentGuardianContact: "01711002233",
    studentMailingAddress: "House: 44, Lane: 1, Mohammadpur, Dhaka: 1207",
  },
  {
    studentName: "Md Tanvir Ahmed",
    studentImage: "",
    studentAge: 24,
    studentFatherName: "Md Delwar Hossain",
    studentMotherName: "Hosne Ara Begum",
    studentEmail: "tanvir.ahmed24@gmail.com",
    studentContact: "01822334455",
    studentGuardianContact: "01622334455",
    studentMailingAddress:
      "House: 63, Road: 11, Sector: 6, Uttara, Dhaka: 1230",
  },
  {
    studentName: "Nusrat Jahan Mim",
    studentImage: "",
    studentAge: 22,
    studentFatherName: "Md Fazlul Karim",
    studentMotherName: "Shirin Sultana",
    studentEmail: "nusrat.mim22@gmail.com",
    studentContact: "01733445566",
    studentGuardianContact: "01533445566",
    studentMailingAddress:
      "House: 8, Block: B, Section: 2, Mirpur, Dhaka: 1216",
  },
  {
    studentName: "Md Sabbir Rahman",
    studentImage: "",
    studentAge: 23,
    studentFatherName: "Md Anwar Hossain",
    studentMotherName: "Mahmuda Khatun",
    studentEmail: "sabbir.rahman23@gmail.com",
    studentContact: "01944556677",
    studentGuardianContact: "01744556677",
    studentMailingAddress: "House: 17, Lane: 4, Khilgaon, Dhaka: 1219",
  },
  {
    studentName: "Afsana Mimi",
    studentImage: "",
    studentAge: 21,
    studentFatherName: "Md Golam Mostofa",
    studentMotherName: "Parveen Akter",
    studentEmail: "afsana.mimi21@gmail.com",
    studentContact: "01655778899",
    studentGuardianContact: "01855778899",
    studentMailingAddress: "House: 29, Road: 9, Banani, Dhaka: 1213",
  },
  {
    studentName: "Md Al Amin",
    studentImage: "",
    studentAge: 26,
    studentFatherName: "Md Yousuf Ali",
    studentMotherName: "Rashida Begum",
    studentEmail: "al.amin26@gmail.com",
    studentContact: "01766223344",
    studentGuardianContact: "01966223344",
    studentMailingAddress:
      "House: 14, Block: F, Section: 11, Pallabi, Dhaka: 1216",
  },
  {
    studentName: "Jannatul Ferdous",
    studentImage: "",
    studentAge: 20,
    studentFatherName: "Md Habibur Rahman",
    studentMotherName: "Selina Akter",
    studentEmail: "jannatul.ferdous20@gmail.com",
    studentContact: "01899001122",
    studentGuardianContact: "01699001122",
    studentMailingAddress: "House: 3, Lane: 6, Wari, Dhaka: 1203",
  },
  {
    studentName: "Md Nayeem Hossain",
    studentImage: "",
    studentAge: 24,
    studentFatherName: "Md Sirajul Islam",
    studentMotherName: "Nazma Begum",
    studentEmail: "nayeem.hossain24@gmail.com",
    studentContact: "01711998877",
    studentGuardianContact: "01911998877",
    studentMailingAddress: "House: 51, Road: 2, Shyamoli, Dhaka: 1207",
  },
  {
    studentName: "Rummana Akter",
    studentImage: "",
    studentAge: 22,
    studentFatherName: "Md Mizanur Rahman",
    studentMotherName: "Lutfun Nahar",
    studentEmail: "rummana.akter22@gmail.com",
    studentContact: "01633445588",
    studentGuardianContact: "01833445588",
    studentMailingAddress:
      "House: 18, Block: A, Section: 12, Pallabi, Dhaka: 1216",
  },
  {
    studentName: "Md Ashraful Islam",
    studentImage: "",
    studentAge: 23,
    studentFatherName: "Md Wahidur Rahman",
    studentMotherName: "Sultana Razia",
    studentEmail: "ashraful.islam23@gmail.com",
    studentContact: "01755112233",
    studentGuardianContact: "01555112233",
    studentMailingAddress: "House: 26, Lane: 3, Jatrabari, Dhaka: 1204",
  },
  {
    studentName: "Sadia Sultana",
    studentImage: "",
    studentAge: 21,
    studentFatherName: "Md Rafiqul Islam",
    studentMotherName: "Kohinoor Begum",
    studentEmail: "sadia.sultana21@gmail.com",
    studentContact: "01877665544",
    studentGuardianContact: "01677665544",
    studentMailingAddress: "House: 33, Road: 5, Lalmatia, Dhaka: 1207",
  },
  {
    studentName: "Md Rezaul Karim",
    studentImage: "",
    studentAge: 25,
    studentFatherName: "Md Motiur Rahman",
    studentMotherName: "Dilruba Yasmin",
    studentEmail: "rezaul.karim25@gmail.com",
    studentContact: "01922334477",
    studentGuardianContact: "01722334477",
    studentMailingAddress:
      "House: 40, Block: E, Section: 7, Mirpur, Dhaka: 1216",
  },
  {
    studentName: "Fahmida Yeasmin",
    studentImage: "",
    studentAge: 20,
    studentFatherName: "Md Shamsul Haque",
    studentMotherName: "Rokeya Begum",
    studentEmail: "fahmida.yeasmin20@gmail.com",
    studentContact: "01644556699",
    studentGuardianContact: "01844556699",
    studentMailingAddress: "House: 7, Lane: 8, Badda, Dhaka: 1212",
  },
  {
    studentName: "Md Jubayer Ahmed",
    studentImage: "",
    studentAge: 24,
    studentFatherName: "Md Ismail Hossain",
    studentMotherName: "Taslima Akter",
    studentEmail: "jubayer.ahmed24@gmail.com",
    studentContact: "01711334455",
    studentGuardianContact: "01911334455",
    studentMailingAddress: "House: 22, Road: 4, Sector: 9, Uttara, Dhaka: 1230",
  },
  {
    studentName: "Nazia Ferdousi",
    studentImage: "",
    studentAge: 22,
    studentFatherName: "Md Aynul Haque",
    studentMotherName: "Momtaz Begum",
    studentEmail: "nazia.ferdousi22@gmail.com",
    studentContact: "01566778811",
    studentGuardianContact: "01766778811",
    studentMailingAddress:
      "House: 15, Block: G, Section: 1, Mirpur, Dhaka: 1216",
  },
];

module.exports = { data: sampleStudents };
