const sampleStudents = [
  {
    studentName: "Sultana Razia",
    studentImage: "",
    studentAge: 22,
    studentFatherName: "Md Mizanur Rahman",
    studentMotherName: "Hosne Ara Begum",
    studentEmail: "sultana.razia@gmail.com",
    studentContact: "01480515542",
    studentGuardianContact: "01795133692",
    studentMailingAddress: "House: 79, Lane: 10, Jatrabari, Dhaka: 1204",
    studentDept: "CSE",
    studentIntake: 48,
    studentClassId: "22234109846",
  },
  {
    studentName: "Sabrina Sultana",
    studentImage: "",
    studentAge: 21,
    studentFatherName: "Md Bazlur Rahman",
    studentMotherName: "Shirina Akter",
    studentEmail: "sabrina.sultana@gmail.com",
    studentContact: "01651115811",
    studentGuardianContact: "01682210473",
    studentMailingAddress: "House: 16, Lane: 6, Tejgaon, Dhaka: 1215",
    studentDept: "BBA",
    studentIntake: 53,
    studentClassId: "22136106052",
  },
  {
    studentName: "Md Mehedi Hasan",
    studentImage: "",
    studentAge: 26,
    studentFatherName: "Md Abdul Latif",
    studentMotherName: "Morzina Begum",
    studentEmail: "mehedi.hasan@gmail.com",
    studentContact: "01532163163",
    studentGuardianContact: "01439638332",
    studentMailingAddress: "House: 28, Lane: 3, Bashundhara R/A, Dhaka: 1229",
    studentDept: "EEE",
    studentIntake: 52,
    studentClassId: "21225109349",
  },
  {
    studentName: "Md Golam Rabbani",
    studentImage: "",
    studentAge: 26,
    studentFatherName: "Md Rustam Ali",
    studentMotherName: "Rokeya Begum",
    studentEmail: "golam.rabbani@gmail.com",
    studentContact: "01781191756",
    studentGuardianContact: "01506101145",
    studentMailingAddress: "House: 42, Lane: 1, Bashundhara R/A, Dhaka: 1229",
    studentDept: "English",
    studentIntake: 51,
    studentClassId: "21213100594",
  },
  {
    studentName: "Shanta Rahman",
    studentImage: "",
    studentAge: 24,
    studentFatherName: "Md Rustam Ali",
    studentMotherName: "Nazma Begum",
    studentEmail: "shanta.rahman@gmail.com",
    studentContact: "01787253922",
    studentGuardianContact: "01541442993",
    studentMailingAddress: "House: 25, Lane: 9, Rampura, Dhaka: 1219",
    studentDept: "CSE",
    studentIntake: 53,
    studentClassId: "22234108871",
  },
  {
    studentName: "Sumaiya Islam",
    studentImage: "",
    studentAge: 20,
    studentFatherName: "Md Aminul Islam",
    studentMotherName: "Nasrin Akter",
    studentEmail: "sumaiya.islam@gmail.com",
    studentContact: "01582200566",
    studentGuardianContact: "01903051310",
    studentMailingAddress: "House: 61, Lane: 6, Shahbagh, Dhaka: 1000",
    studentDept: "BBA",
    studentIntake: 51,
    studentClassId: "22136103993",
  },
  {
    studentName: "Md Anisur Rahman",
    studentImage: "",
    studentAge: 20,
    studentFatherName: "Md Idris Ali",
    studentMotherName: "Morzina Begum",
    studentEmail: "anisur.rahman@gmail.com",
    studentContact: "01986676508",
    studentGuardianContact: "01328320827",
    studentMailingAddress: "House: 53, Lane: 7, Farmgate, Dhaka: 1215",
    studentDept: "EEE",
    studentIntake: 50,
    studentClassId: "21225103411",
  },
  {
    studentName: "Md Tanvir Ahmed",
    studentImage: "",
    studentAge: 20,
    studentFatherName: "Md Rustam Ali",
    studentMotherName: "Dilruba Yasmin",
    studentEmail: "tanvir.ahmed@gmail.com",
    studentContact: "01315360898",
    studentGuardianContact: "01615515976",
    studentMailingAddress: "House: 59, Lane: 8, Shyamoli, Dhaka: 1207",
    studentDept: "English",
    studentIntake: 51,
    studentClassId: "21213100066",
  },
  {
    studentName: "Md Sabbir Rahman",
    studentImage: "",
    studentAge: 23,
    studentFatherName: "Md Idris Ali",
    studentMotherName: "Nasrin Akter",
    studentEmail: "sabbir.rahman@gmail.com",
    studentContact: "01388777426",
    studentGuardianContact: "01323024346",
    studentMailingAddress: "House: 41, Lane: 1, Mohammadpur, Dhaka: 1207",
    studentDept: "CSE",
    studentIntake: 50,
    studentClassId: "22234105835",
  },
  {
    studentName: "Md Al Amin",
    studentImage: "",
    studentAge: 24,
    studentFatherName: "Md Nurul Islam",
    studentMotherName: "Halima Khatun",
    studentEmail: "al.amin@gmail.com",
    studentContact: "01910240765",
    studentGuardianContact: "01527834004",
    studentMailingAddress: "House: 70, Lane: 1, Khilgaon, Dhaka: 1219",
    studentDept: "BBA",
    studentIntake: 53,
    studentClassId: "22136102683",
  },
  {
    studentName: "Rupa Khatun",
    studentImage: "",
    studentAge: 24,
    studentFatherName: "Md Iqbal Hossain",
    studentMotherName: "Ferdousi Begum",
    studentEmail: "rupa.khatun@gmail.com",
    studentContact: "01652341254",
    studentGuardianContact: "01557254507",
    studentMailingAddress: "House: 71, Lane: 9, Pallabi, Dhaka: 1216",
    studentDept: "EEE",
    studentIntake: 48,
    studentClassId: "21225100088",
  },
  {
    studentName: "Md Emon Khan",
    studentImage: "",
    studentAge: 26,
    studentFatherName: "Md Habibur Rahman",
    studentMotherName: "Shirin Sultana",
    studentEmail: "emon.khan@gmail.com",
    studentContact: "01534638870",
    studentGuardianContact: "01652218480",
    studentMailingAddress: "House: 78, Lane: 1, Dhanmondi, Dhaka: 1209",
    studentDept: "English",
    studentIntake: 50,
    studentClassId: "21213102793",
  },
  {
    studentName: "Md Rezaul Karim",
    studentImage: "",
    studentAge: 20,
    studentFatherName: "Md Nazrul Islam",
    studentMotherName: "Nasrin Akter",
    studentEmail: "rezaul.karim@gmail.com",
    studentContact: "01417245640",
    studentGuardianContact: "01471574341",
    studentMailingAddress: "House: 41, Lane: 2, Farmgate, Dhaka: 1215",
    studentDept: "CSE",
    studentIntake: 52,
    studentClassId: "22234102067",
  },
  {
    studentName: "Nasrin Sultana",
    studentImage: "",
    studentAge: 26,
    studentFatherName: "Md Wahidur Rahman",
    studentMotherName: "Nurjahan Begum",
    studentEmail: "nasrin.sultana@gmail.com",
    studentContact: "01709523617",
    studentGuardianContact: "01993842334",
    studentMailingAddress: "House: 80, Lane: 7, Gulshan, Dhaka: 1212",
    studentDept: "BBA",
    studentIntake: 49,
    studentClassId: "22136103116",
  },
  {
    studentName: "Jannatul Ferdous",
    studentImage: "",
    studentAge: 19,
    studentFatherName: "Md Zakir Hossain",
    studentMotherName: "Nazma Begum",
    studentEmail: "jannatul.ferdous@gmail.com",
    studentContact: "01757252515",
    studentGuardianContact: "01759655788",
    studentMailingAddress: "House: 71, Lane: 10, Banani, Dhaka: 1213",
    studentDept: "EEE",
    studentIntake: 50,
    studentClassId: "21225106029",
  },
  {
    studentName: "Nazia Ferdousi",
    studentImage: "",
    studentAge: 19,
    studentFatherName: "Md Anwarul Haque",
    studentMotherName: "Kohinoor Begum",
    studentEmail: "nazia.ferdousi@gmail.com",
    studentContact: "01954807462",
    studentGuardianContact: "01685410152",
    studentMailingAddress: "House: 31, Lane: 4, Farmgate, Dhaka: 1215",
    studentDept: "English",
    studentIntake: 53,
    studentClassId: "21213106261",
  },
  {
    studentName: "Md Shazzad Hossain",
    studentImage: "",
    studentAge: 24,
    studentFatherName: "Md Jahangir Mia",
    studentMotherName: "Shahinur Begum",
    studentEmail: "shazzadmail1@gmail.com",
    studentContact: "01766032333",
    studentGuardianContact: "01816898357",
    studentMailingAddress: "House: 37, Lane: 5, Block: A, Section: 6, Mirpur, Dhaka: 1216",
    studentDept: "CSE",
    studentIntake: 50,
    studentClassId: "22234103110",
  },
  {
    studentName: "Md Shafiul Alam",
    studentImage: "",
    studentAge: 23,
    studentFatherName: "Md Yousuf Ali",
    studentMotherName: "Shahida Begum",
    studentEmail: "shafiul.alam@gmail.com",
    studentContact: "01801405321",
    studentGuardianContact: "01398311521",
    studentMailingAddress: "House: 41, Lane: 7, Shahbagh, Dhaka: 1000",
    studentDept: "BBA",
    studentIntake: 48,
    studentClassId: "22136103869",
  },
  {
    studentName: "Md Foysal Ahmed",
    studentImage: "",
    studentAge: 20,
    studentFatherName: "Md Ismail Hossain",
    studentMotherName: "Shefali Begum",
    studentEmail: "foysal.ahmed@gmail.com",
    studentContact: "01586587491",
    studentGuardianContact: "01840608169",
    studentMailingAddress: "House: 57, Lane: 7, Malibagh, Dhaka: 1217",
    studentDept: "EEE",
    studentIntake: 49,
    studentClassId: "21225103498",
  },
  {
    studentName: "Md Kamrul Hasan",
    studentImage: "",
    studentAge: 21,
    studentFatherName: "Md Aminul Islam",
    studentMotherName: "Halima Khatun",
    studentEmail: "kamrul.hasan@gmail.com",
    studentContact: "01383300410",
    studentGuardianContact: "01695676958",
    studentMailingAddress: "House: 7, Lane: 1, Rampura, Dhaka: 1219",
    studentDept: "English",
    studentIntake: 50,
    studentClassId: "21213102980",
  },
  {
    studentName: "Md Fahim Faisal",
    studentImage: "",
    studentAge: 19,
    studentFatherName: "Md Rafiqul Islam",
    studentMotherName: "Rowshan Ara",
    studentEmail: "fahim.faisal@gmail.com",
    studentContact: "01937685307",
    studentGuardianContact: "01906192834",
    studentMailingAddress: "House: 36, Lane: 9, Shahbagh, Dhaka: 1000",
    studentDept: "CSE",
    studentIntake: 52,
    studentClassId: "22234101639",
  },
  {
    studentName: "Rummana Akter",
    studentImage: "",
    studentAge: 24,
    studentFatherName: "Md Zahirul Haque",
    studentMotherName: "Rokshana Begum",
    studentEmail: "rummana.akter@gmail.com",
    studentContact: "01999684877",
    studentGuardianContact: "01983827563",
    studentMailingAddress: "House: 60, Lane: 6, Farmgate, Dhaka: 1215",
    studentDept: "BBA",
    studentIntake: 48,
    studentClassId: "22136105895",
  },
  {
    studentName: "Md Sohel Rana",
    studentImage: "",
    studentAge: 20,
    studentFatherName: "Md Delwar Hossain",
    studentMotherName: "Hosne Ara Begum",
    studentEmail: "sohel.rana@gmail.com",
    studentContact: "01661018546",
    studentGuardianContact: "01969764454",
    studentMailingAddress: "House: 64, Lane: 5, Khilgaon, Dhaka: 1219",
    studentDept: "EEE",
    studentIntake: 48,
    studentClassId: "21225107445",
  },
  {
    studentName: "Md Saiful Islam",
    studentImage: "",
    studentAge: 21,
    studentFatherName: "Md Motiur Rahman",
    studentMotherName: "Rezia Begum",
    studentEmail: "saiful.islam@gmail.com",
    studentContact: "01641561244",
    studentGuardianContact: "01538155446",
    studentMailingAddress: "House: 41, Lane: 8, Lalmatia, Dhaka: 1207",
    studentDept: "English",
    studentIntake: 52,
    studentClassId: "21213105925",
  },
  {
    studentName: "Sharmin Jahan",
    studentImage: "",
    studentAge: 25,
    studentFatherName: "Md Abul Kashem",
    studentMotherName: "Amena Begum",
    studentEmail: "sharmin.jahan@gmail.com",
    studentContact: "01848442645",
    studentGuardianContact: "01551749383",
    studentMailingAddress: "House: 9, Lane: 10, Tejgaon, Dhaka: 1215",
    studentDept: "CSE",
    studentIntake: 51,
    studentClassId: "22234103012",
  },
  {
    studentName: "Md Zahid Hasan",
    studentImage: "",
    studentAge: 26,
    studentFatherName: "Md Rafiqul Alam",
    studentMotherName: "Morzina Begum",
    studentEmail: "zahid.hasan@gmail.com",
    studentContact: "01470488071",
    studentGuardianContact: "01714711974",
    studentMailingAddress: "House: 61, Lane: 3, Mohammadpur, Dhaka: 1207",
    studentDept: "BBA",
    studentIntake: 51,
    studentClassId: "22136109806",
  },
  {
    studentName: "Md Ovi Rahman",
    studentImage: "",
    studentAge: 21,
    studentFatherName: "Md Zahirul Haque",
    studentMotherName: "Nurjahan Begum",
    studentEmail: "ovi.rahman@gmail.com",
    studentContact: "01587370359",
    studentGuardianContact: "01448974127",
    studentMailingAddress: "House: 80, Lane: 1, Banani, Dhaka: 1213",
    studentDept: "EEE",
    studentIntake: 53,
    studentClassId: "21225109807",
  },
  {
    studentName: "Md Masud Rana",
    studentImage: "",
    studentAge: 19,
    studentFatherName: "Md Delwar Hossain",
    studentMotherName: "Rupa Begum",
    studentEmail: "masud.rana@gmail.com",
    studentContact: "01733103313",
    studentGuardianContact: "01982475920",
    studentMailingAddress: "House: 31, Lane: 1, Jatrabari, Dhaka: 1204",
    studentDept: "English",
    studentIntake: 50,
    studentClassId: "21213105661",
  },
  {
    studentName: "Tania Akter",
    studentImage: "",
    studentAge: 26,
    studentFatherName: "Md Shahidul Islam",
    studentMotherName: "Shahnaz Begum",
    studentEmail: "tania.akter@gmail.com",
    studentContact: "01545167076",
    studentGuardianContact: "01491242807",
    studentMailingAddress: "House: 24, Lane: 3, Motijheel, Dhaka: 1000",
    studentDept: "CSE",
    studentIntake: 48,
    studentClassId: "22234100012",
  },
  {
    studentName: "Shirin Akter",
    studentImage: "",
    studentAge: 20,
    studentFatherName: "Md Alamgir Hossain",
    studentMotherName: "Rezia Begum",
    studentEmail: "shirin.akter@gmail.com",
    studentContact: "01856353726",
    studentGuardianContact: "01623949884",
    studentMailingAddress: "House: 46, Lane: 1, Lalmatia, Dhaka: 1207",
    studentDept: "BBA",
    studentIntake: 53,
    studentClassId: "22136105551",
  },
  {
    studentName: "Md Tarequl Islam",
    studentImage: "",
    studentAge: 25,
    studentFatherName: "Md Selim Reza",
    studentMotherName: "Ferdousi Begum",
    studentEmail: "tarequl.islam@gmail.com",
    studentContact: "01683846109",
    studentGuardianContact: "01704146570",
    studentMailingAddress: "House: 15, Lane: 6, Dhanmondi, Dhaka: 1209",
    studentDept: "EEE",
    studentIntake: 51,
    studentClassId: "21225105285",
  },
  {
    studentName: "Md Mahmudul Hasan",
    studentImage: "",
    studentAge: 26,
    studentFatherName: "Md Rafiqul Islam",
    studentMotherName: "Salma Khatun",
    studentEmail: "mahmudul.hasan@gmail.com",
    studentContact: "01308492300",
    studentGuardianContact: "01592971807",
    studentMailingAddress: "House: 33, Lane: 8, Wari, Dhaka: 1203",
    studentDept: "English",
    studentIntake: 51,
    studentClassId: "21213107970",
  },
  {
    studentName: "Md Rakibul Hasan",
    studentImage: "",
    studentAge: 25,
    studentFatherName: "Md Kabir Hossain",
    studentMotherName: "Ferdousi Begum",
    studentEmail: "rakibul.hasan@gmail.com",
    studentContact: "01838489641",
    studentGuardianContact: "01432748702",
    studentMailingAddress: "House: 80, Lane: 4, Farmgate, Dhaka: 1215",
    studentDept: "CSE",
    studentIntake: 52,
    studentClassId: "22234106305",
  },
  {
    studentName: "Rina Akter",
    studentImage: "",
    studentAge: 22,
    studentFatherName: "Md Zahirul Haque",
    studentMotherName: "Rupa Begum",
    studentEmail: "rina.akter@gmail.com",
    studentContact: "01349657597",
    studentGuardianContact: "01394602119",
    studentMailingAddress: "House: 37, Lane: 3, Pallabi, Dhaka: 1216",
    studentDept: "BBA",
    studentIntake: 48,
    studentClassId: "22136109409",
  },
  {
    studentName: "Kanta Islam",
    studentImage: "",
    studentAge: 20,
    studentFatherName: "Md Bazlur Rahman",
    studentMotherName: "Nasrin Akter",
    studentEmail: "kanta.islam@gmail.com",
    studentContact: "01749061903",
    studentGuardianContact: "01414546124",
    studentMailingAddress: "House: 50, Lane: 5, Khilgaon, Dhaka: 1219",
    studentDept: "EEE",
    studentIntake: 48,
    studentClassId: "21225105331",
  },
  {
    studentName: "Md Hasibul Islam",
    studentImage: "",
    studentAge: 23,
    studentFatherName: "Md Nazrul Islam",
    studentMotherName: "Rabia Khatun",
    studentEmail: "hasibul.islam@gmail.com",
    studentContact: "01715210157",
    studentGuardianContact: "01748571329",
    studentMailingAddress: "House: 72, Lane: 1, Dhanmondi, Dhaka: 1209",
    studentDept: "English",
    studentIntake: 51,
    studentClassId: "21213101036",
  },
  {
    studentName: "Sultana Parvin",
    studentImage: "",
    studentAge: 19,
    studentFatherName: "Md Rustam Ali",
    studentMotherName: "Nurjahan Begum",
    studentEmail: "sultana.parvin@gmail.com",
    studentContact: "01900741669",
    studentGuardianContact: "01642397811",
    studentMailingAddress: "House: 32, Lane: 8, Lalmatia, Dhaka: 1207",
    studentDept: "CSE",
    studentIntake: 53,
    studentClassId: "22234102559",
  },
  {
    studentName: "Priya Rani",
    studentImage: "",
    studentAge: 19,
    studentFatherName: "Md Iqbal Hossain",
    studentMotherName: "Shefali Begum",
    studentEmail: "priya.rani@gmail.com",
    studentContact: "01944790334",
    studentGuardianContact: "01314789646",
    studentMailingAddress: "House: 23, Lane: 5, Banani, Dhaka: 1213",
    studentDept: "BBA",
    studentIntake: 52,
    studentClassId: "22136109749",
  },
  {
    studentName: "Md Naimur Rahman",
    studentImage: "",
    studentAge: 19,
    studentFatherName: "Md Shahjahan Ali",
    studentMotherName: "Nurjahan Begum",
    studentEmail: "naimur.rahman@gmail.com",
    studentContact: "01771497843",
    studentGuardianContact: "01829963177",
    studentMailingAddress: "House: 54, Lane: 5, Dhanmondi, Dhaka: 1209",
    studentDept: "EEE",
    studentIntake: 50,
    studentClassId: "21225104159",
  },
  {
    studentName: "Taslima Akter",
    studentImage: "",
    studentAge: 19,
    studentFatherName: "Md Fazlul Karim",
    studentMotherName: "Fatema Begum",
    studentEmail: "taslima.akter@gmail.com",
    studentContact: "01418304110",
    studentGuardianContact: "01362860136",
    studentMailingAddress: "House: 22, Lane: 5, Pallabi, Dhaka: 1216",
    studentDept: "English",
    studentIntake: 53,
    studentClassId: "21213105609",
  },
];

module.exports = { data: sampleStudents };
